### ISSUE TITLE
KeyError: 'model'

### ISSUE THREAD

**Issue by Tracy-git** [Junjue-Wang/LoveDA#35]
when i use pretrained model to evaluate ,output follow error, it seems ever has some problems??
Traceback (most recent call last):
  File "D:/parttimeJOB/project/Semantic_Segmentation/eval.py", line 78, in <module>
    evaluate(args.ckpt_path, args.config_path, args.tta)
  File "D:/parttimeJOB/project/Semantic_Segmentation/eval.py", line 34, in evaluate
    model_state_dict = load_model_state_dict_from_ckpt(ckpt_path)
  File "c:\users\lunchsolace\downloads\ever-master\ever\core\checkpoint.py", line 160, in load_model_state_dict_from_ckpt
    statedict = ckpt[CheckPoint.MODEL]
KeyError: 'model'

**Comment by ziegn** [comment]
How did you finally solve this problem?

**Comment by simonep1052** [comment]
May I ask you how you solved the error please, @Tracy-git? I also have the same error.
