### ISSUE TITLE
what is 'ever' package? It seems like some file missing.

### ISSUE THREAD

**Issue by Linwei-Chen** [Junjue-Wang/LoveDA#36]
Traceback (most recent call last):
  File "CBST_train.py", line 6, in <module>
    from eval import evaluate
  File "/media/ubuntu/2TB/code/AerialSeg/LoveDA/Unsupervised_Domian_Adaptation/eval.py", line 1, in <module>
    from data.loveda import LoveDALoader
  File "/media/ubuntu/2TB/code/AerialSeg/LoveDA/Unsupervised_Domian_Adaptation/data/loveda.py", line 9, in <module>
    from ever.interface import ConfigurableMixin
ModuleNotFoundError: No module named 'ever.interface'

**Comment by Linwei-Chen** [comment]
pip install ever-beta==0.2.3
Problem is solved.
