### ISSUE TITLE
ModuleNotFoundError: No module named 'ever'

### ISSUE THREAD

**Issue by SxyNoPeace** [Junjue-Wang/LoveDA#41]
When I execute    bash ./scripts/predict_cbst.sh ，The following error occurred：

Traceback (most recent call last):
  File "predict.py", line 1, in <module>
    from data.loveda import LoveDALoader
  File "/home/chen/experiment/remote_sensing/Unsupervised_Domian_Adaptation/data/loveda.py", line 9, in <module>
    from ever.interface import ConfigurableMixin
ModuleNotFoundError: No module named 'ever'

How can I find this module? I hope to get your reply. Thank you

**Comment by Junjue-Wang** [comment]
please see my readme to install it

**Comment by wuyehong** [comment]
> When I execute bash ./scripts/predict_cbst.sh ，The following error occurred：
> 
> Traceback (most recent call last): File "predict.py", line 1, in from data.loveda import LoveDALoader File "/home/chen/experiment/remote_sensing/Unsupervised_Domian_Adaptation/data/loveda.py", line 9, in from ever.interface import ConfigurableMixin ModuleNotFoundError: No module named 'ever'
> 
> How can I find this module? I hope to get your reply. Thank you

您好，这个问题您解决了吗？
