### ISSUE TITLE
Can run with One GPU in this work?

### ISSUE THREAD

**Issue by kukujoyyo** [Junjue-Wang/LoveDA#52]
**Shall we run this work with One GPU? If possible how to set parameters？ **

I'v got the issue below:

PS F:\Models\LoveDA-master\Semantic_Segmentation> bash ./scripts/train_hrnetw32.sh
NOTE: Redirects are currently not supported in Windows or MacOs.
Init Trainer
Set Seed Torch
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    trainer = er.trainer.get_trainer('th_amp_ddp')()
  File "D:\ProgramData\Anaconda3\lib\site-packages\ever\api\trainer\th_amp_ddp_trainer.py", line 77, in __init__
    torch.cuda.set_device(self.args.local_rank)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 311, in set_device
    device = _get_device_index(device)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\_utils.py", line 537, in _get_device_index
    'or an integer, but got:{}'.format(device))
ValueError: Expected a torch.device with a specified index or an integer, but got:None
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 108252) of binary: D:\ProgramData\Anaconda3\python.exe
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\run.py", line 724, in main
    run(args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\run.py", line 718, in run
    )(*cmd_args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-13_13:10:33
  host      : KWPAACQRFTY8V05
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 108252)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Junjue-Wang** [comment]
Please refer to the Pytorch document

**Comment by Sixsheepdad** [comment]
> **Shall we run this work with One GPU? If possible how to set parameters？ **
> 
> I'v got the issue below:
> 
> # PS F:\Models\LoveDA-master\Semantic_Segmentation> bash ./scripts/train_hrnetw32.sh
> NOTE: Redirects are currently not supported in Windows or MacOs.
> Init Trainer
> Set Seed Torch
> Traceback (most recent call last):
> File "train.py", line 79, in
> trainer = er.trainer.get_trainer('th_amp_ddp')()
> File "D:\ProgramData\Anaconda3\lib\site-packages\ever\api\trainer\th_amp_ddp_trainer.py", line 77, in **init**
> torch.cuda.set_device(self.args.local_rank)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\cuda__init__.py", line 311, in set_device
> device = _get_device_index(device)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\cuda_utils.py", line 34, in _get_device_index
> return _torch_get_device_index(device, optional, allow_cpu)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch_utils.py", line 537, in _get_device_index
> 'or an integer, but got:{}'.format(device))
> ValueError: Expected a torch.device with a specified index or an integer, but got:None
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 108252) of binary: D:\ProgramData\Anaconda3\python.exe
> Traceback (most recent call last):
> File "D:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\ProgramData\Anaconda3\Scripts\torchrun.exe__main__.py", line 7, in File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\elastic\multiprocessing\errors__init__.py", line 345, in wrapper
> return f(*args, **kwargs)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\run.py", line 724, in main
> run(args)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\run.py", line 718, in run
> )(*cmd_args)
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 131, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "D:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launcher\api.py", line 247, in launch_agent
> failures=result.failures,
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## train.py FAILED
> ## Failures:
> <NO_OTHER_FAILURES>
> # Root Cause (first observed failure):
> [0]:
> time : 2022-11-13_13:10:33
> host : KWPAACQRFTY8V05
> rank : 0 (local_rank: 0)
> exitcode : 1 (pid: 108252)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Did you solve this problem?

**Comment by oskejnbfnn** [comment]
I have encountered the same problem. Have you resolved it

**Comment by Sixsheepdad** [comment]
Sorry, I didn't solve that problem.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 11, 2024 21:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Junjue-Wang/LoveDA] Can run with One GPU in this work? (Issue#52)




 
I have encountered the same problem. Have you resolved it

**Comment by Z-in-B** [comment]
try adding the '__local_rank' argument in the '*.sh' file.
