### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by kukujoyyo** [Junjue-Wang/LoveDA#54]
Traceback (most recent call last).
File ""home/libowen/LoveDA-master/Semantic Segmentation/predict.py", line 52, in smodule>
predict test(argsckpt path, args.config path, args.out dir)File "/home/libowen/LoveDA-master/Semantic Segmentation/predictpy", line 37, in predict test
modelload state dictmodel state dict)
File "home/libowen/.conda/envs/bw/ib/python3.8/site-packages/torch/nn/modules/module,py", line 1667, in load state dictraise RuntimeError(Error(s) in loading state dict for f:init+.format(RuntimeError: Error(s) in loading state dict for HRNetFusion.
Missing keys) in state dict: "ackbone.het.conv1.weight"ackbone hmet bn1.weight, "ackbone hretbn1.bias""backbone hmet bn1.running mean"

**Comment by Junjue-Wang** [comment]
ackbone.het.conv1.weight"ackbone hmet bn1.weight, "ackbone hretbn1.bias

It seems you have wrong keys.
