### ISSUE TITLE
求助，CodaLab平台提交结果报错，怎么办啊？

### ISSUE THREAD

**Issue by Voruarn** [Junjue-Wang/LoveDA#75]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpYybxmR/run/program/evaluate.py:153: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  gt = imread(truthp).astype(np.float) - 1
Traceback (most recent call last):
  File "/tmp/codalab/tmpYybxmR/run/program/evaluate.py", line 158, in 
    metric.forward(gt[valid_inds], mask[valid_inds])
  File "/tmp/codalab/tmpYybxmR/run/program/evaluate.py", line 22, in forward
    cm = sparse.coo_matrix((v, (y_true, y_pred)), shape=(self.num_classes, self.num_classes), dtype=np.float32)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 196, in __init__
    self._check()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 285, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions

**Comment by Junjue-Wang** [comment]
Please refer to https://github.com/Junjue-Wang/LoveDA/issues/73

**Comment by Voruarn** [comment]
收到，谢谢
