### ISSUE TITLE
求助，CodaLab平台提交结果报错

### ISSUE THREAD

**Issue by LC5123** [Junjue-Wang/LoveDA#83]
我遇到了和#75一样的问题，也参考了#73的解决方式，我submit的是一个.zip文件，压缩了包含1796张预测图的文件夹。我写了一个脚本来检查输出图片的格式，应该是uint8 [1024,1024]没错的。我的用户名是Hectorcliu
我遇到的问题如下：
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpFUWE6z/run/program/evaluate.py:153: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  gt = imread(truthp).astype(np.float) - 1
Traceback (most recent call last):
  File "/tmp/codalab/tmpFUWE6z/run/program/evaluate.py", line 158, in 
    metric.forward(gt[valid_inds], mask[valid_inds])
  File "/tmp/codalab/tmpFUWE6z/run/program/evaluate.py", line 22, in forward
    cm = sparse.coo_matrix((v, (y_true, y_pred)), shape=(self.num_classes, self.num_classes), dtype=np.float32)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 196, in __init__
    self._check()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 285, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions
以下是我编写的检查脚本：
import glob
import numpy as np
from PIL import Image

img_names = glob.glob("./results/*.png")
for img_name in img_names:
    img = np.asarray(Image.open(img_name))
    if img.dtype != np.uint8 or img.shape[0] != 1024 or img.shape[1] != 1024 or img.ndim != 2:
        print(img_name)
麻烦大佬帮忙看一下，谢谢！

**Comment by AZong76** [comment]
请问您解决了吗？

**Comment by AZong76** [comment]
我遇到了相同的问题

**Comment by xyz-to** [comment]
同样的问题，求解决，我的名字是Xiong_yz

**Comment by Junjue-Wang** [comment]
应该全选图片压缩，而不是压缩文件夹

**Comment by xyz-to** [comment]
您好，文件夹问题我在最后几次提交时改正过来了，您能帮我在指导一下嘛？万分感谢

**Comment by Junjue-Wang** [comment]
我检查了一下你的提交结果，发现你是24位的，提交图片应该是1024x1024，不能是1024x1024x3。

**Comment by xyz-to** [comment]
感谢，我已经能成功提交。
