### ISSUE TITLE
Codalab submission issue

### ISSUE THREAD

**Issue by guneetmutreja** [Junjue-Wang/LoveDA#89]
Hello Junjue,

I have been trying to submit my results ot the Codalab portal but my submission is failing with the following error. I have already seen some related issues and have tried all solutions like image size should be 1024X1024 and should be unit8. ALso I have verified that the images pixel values lie between [1-7]. Not sure now what could be an issue. Aould you mind helping me out with the identification of the issue?
My username is: guneetmutreja

Thanks a ton!

"/tmp/codalab/tmpFefcQf/run/program/evaluate.py:153: DeprecationWarning: np.float is a deprecated alias for the builtin float. To silence this warning, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  gt = imread(truthp).astype(np.float) - 1
Traceback (most recent call last):
  File "/tmp/codalab/tmpFefcQf/run/program/evaluate.py", line 158, in 
    metric.forward(gt[valid_inds], mask[valid_inds])
  File "/tmp/codalab/tmpFefcQf/run/program/evaluate.py", line 22, in forward
    cm = sparse.coo_matrix((v, (y_true, y_pred)), shape=(self.num_classes, self.num_classes), dtype=np.float32)
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/coo.py", line 196, in _init
    self._check()
  File "/opt/conda/lib/python3.9/site-packages/scipy/sparse/_coo.py", line 285, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions"

**Comment by bigseamountain** [comment]
hi Have you solved this problem

**Comment by Junjue-Wang** [comment]
You should check your predictions to make them [1024 x 1024], only two dimensions. Not [1024x1024 x1]

**Comment by guneetmutreja** [comment]
@bigseamountain the issue was resolved with the suggestion that @Junjue-Wang gave.
Thank you @Junjue-Wang, closing the issue.
